# Generated by Django 5.1.6 on 2025-02-17 14:29

import portfolio.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Aname', models.CharField(max_length=100, verbose_name='Name')),
                ('Adate_of_birth', models.DateField(verbose_name='Date of birth')),
                ('Aaddress', models.CharField(max_length=200, verbose_name='Address')),
                ('Azip_code', models.CharField(max_length=20, verbose_name='Zip Code ')),
                ('Aemail', models.EmailField(max_length=254, verbose_name='Email')),
                ('Aphone', models.CharField(max_length=20, verbose_name='Phone')),
                ('Aabout_text', models.TextField(help_text='Short bio or introduction', verbose_name='Description')),
                ('Aprofile_image', models.ImageField(blank=True, null=True, upload_to='about/', verbose_name='Image')),
            ],
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BPtitle', models.CharField(max_length=200)),
                ('BPslug', models.SlugField(unique=True)),
                ('BPcontent', models.TextField()),
                ('BPcreated_at', models.DateTimeField(auto_now_add=True)),
                ('BPupdated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CMname', models.CharField(max_length=100)),
                ('CMemail', models.EmailField(max_length=254)),
                ('CMsubject', models.CharField(max_length=200)),
                ('CMmessage', models.TextField()),
                ('CMnamecreated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ptitle', models.CharField(max_length=200, verbose_name='Title')),
                ('Pdescription', models.TextField(verbose_name='Description')),
                ('Pimage', models.ImageField(blank=True, null=True, upload_to=portfolio.models.project_image_upload, verbose_name='Images')),
                ('Pcategory', models.CharField(blank=True, max_length=100, null=True, verbose_name='Category')),
                ('Pproject_url', models.URLField(blank=True, null=True, verbose_name='Project Url')),
            ],
        ),
        migrations.CreateModel(
            name='ResumeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RIitem_type', models.CharField(choices=[('education', 'Education'), ('experience', 'Experience')], max_length=20, verbose_name='Type')),
                ('RItitle', models.CharField(help_text='Degree or Position', max_length=200, verbose_name='Title')),
                ('RIinstitution_or_company', models.CharField(max_length=200, verbose_name='Institution or Company')),
                ('RIfrom_year', models.IntegerField(verbose_name='From')),
                ('RIto_year', models.IntegerField(verbose_name='To')),
                ('RIdescription', models.TextField(verbose_name='Description')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Stitle', models.CharField(max_length=100, verbose_name='Title')),
                ('Sdescription', models.TextField(verbose_name='Description')),
                ('Sicon', models.CharField(help_text='CSS class for icon (e.g., FontAwesome icon class).', max_length=50, verbose_name='Icon')),
            ],
        ),
        migrations.CreateModel(
            name='SiteStatistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SSawards', models.PositiveIntegerField(default=0, verbose_name='Awards')),
                ('SScomplete_projects', models.PositiveIntegerField(default=0, verbose_name='Complate Projects')),
                ('SShappy_customers', models.PositiveIntegerField(default=0, verbose_name='Happy Customers')),
                ('SScups_of_coffee', models.PositiveIntegerField(default=0, verbose_name='Cups of Coffee')),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Sname', models.CharField(max_length=100, verbose_name='Name')),
                ('Sproficiency', models.PositiveIntegerField(help_text='Percentage (0-100).', verbose_name='Proficiency')),
            ],
        ),
    ]
