# Generated by Django 5.1.6 on 2025-02-18 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='Ajop_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Jop Name'),
        ),
    ]
