# Generated by Django 5.1.6 on 2025-02-19 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_remove_service_sicon'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='BPimage',
            field=models.ImageField(blank=True, null=True, upload_to='blog_posts/', verbose_name='image'),
        ),
    ]
